### ISSUE TITLE
Doesn't work with byte[]

### ISSUE THREAD

**Issue by Rudnytskyi** [KorzhCom/EasyData#40]
It is possible to configure EasyData to be able to work with byte arrays?
byte[] fields are not displayed for editing

**Comment by korzh** [comment]
Yes, that because this type usually represents a BLOB field, and BLOB fields are used to store binary data (images, not-textual files, etc). What editor would you like to see for these fields?

**Comment by korzh** [comment]
OK. We will add this option in one of the next updates.

**Comment by Rudnytskyi** [comment]
It would be great! Thank you!

**Comment by antifree** [comment]
Done in version 1.3.0

**Comment by Rudnytskyi** [comment]
sorry, but this still doesn't work (
doesn't display column with byte[] type[](url)
[https://imgur.com/a/N95mMFX](url)

**Comment by korzh** [comment]
It was not supposed to show it in the view. We just added a possibility to set it in the Add/Edit Record dialogs (by uploading a file)

**Comment by korzh** [comment]
Your link on the screenshot does not work, by the way.

**Comment by Rudnytskyi** [comment]
> Your link on the screenshot does not work, by the way.

just copy text link and paste in browser

**Comment by korzh** [comment]
Hm. So, it shows the value for the Type field incorrectly and does not show the Data field at all, right?

Could you please attach the response body for the "Get Metadata" request (it's the first one that usually looks like `/api/easydata/models/SomeModelID`).
We will try to reproduce the problem and to fix it.

**Comment by Rudnytskyi** [comment]
> Hm. So, it shows the value for the Type field incorrectly and does not show the Data field at all, right?
> 
> Could you please attach the response body for the "Get Metadata" request (it's the first one that usually looks like `/api/easydata/models/SomeModelID`).
> We will try to reproduce the problem and to fix it.

Request URL:
/api/easydata/models/EasyData/crud/ImageData/fetch

Respose:
```
{
	"result": "ok",
	"meta": {
		"totalRecords": 20
	},
	"resultSet": {
		"cols": [
			{
				"id": "ImageData.Id",
				"isAggr": false,
				"label": "Id",
				"type": 4,
				"originAttrId": "ImageData.Id",
				"dfmt": null,
				"gfct": null,
				"style": {
					"Alignment": 0
				}
			},
			{
				"id": "ImageData.Data",
				"isAggr": false,
				"label": "Data",
				"type": 15,
				"originAttrId": "ImageData.Data",
				"dfmt": null,
				"gfct": null,
				"style": {
					"Alignment": 0
				}
			},
			{
				"id": "ImageData.ImageName",
				"isAggr": false,
				"label": "Image Name",
				"type": 1,
				"originAttrId": "ImageData.ImageName",
				"dfmt": null,
				"gfct": null,
				"style": {
					"Alignment": 0
				}
			},
			{
				"id": "ImageData.LinkedId",
				"isAggr": false,
				"label": "Linked Id",
				"type": 4,
				"originAttrId": "ImageData.LinkedId",
				"dfmt": null,
				"gfct": null,
				"style": {
					"Alignment": 0
				}
			},
			{
				"id": "ImageData.Type",
				"isAggr": false,
				"label": "Type",
				"type": 4,
				"originAttrId": "ImageData.Type",
				"dfmt": "{0:SAnimal=1|User=2}",
				"gfct": null,
				"style": {
					"Alignment": 0
				}
			}
		],
		"rows": [
			[
				2,
				"/9j/4AAQSkZJRgABAQEBLAEsAAD/2wCEAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBABAwMDBAMECAQECBALCQsQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEP/AABEIASwBLAMBEQACEQEDEQH/xAGiAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoLEQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP1ToAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKAPMvin+0z8A/gos6fFD4r+HNCu7dBI9hLeLJekEZXFtHulORyMLzQB8WeMP+C0HwhXxHfeHvCPgbxMdHa1litfEskcTPHdEYjk+wsymSEHBIMqORkYBoA9x/Yf/bx8JftXeHdQ07XYbLw/448PRiTU7BJSLa6t87Rd2xkO4R5wGRiWQlQSQQSAfVsckcsayxOro4DKynIIPQg0AOoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgD4B/bV/wCCn3gT4V6F4i+F/wAJrfXLv4ivFJYG5u9NnsIdGdlwZiJ1SSSRQcoFXaTglsDBAPxh1nWdX8Rarda5r+qXepajfStNdXd3M0008h6u7sSzMfUmgCnQAqSPGSY3ZSRg4OOKAP2Q/wCCPPxi8LeJvh5qvwuj8Q6nb+IdARZ5tEu7xri1lgLYF7ZiTLw5JCTRKxjDbHVU8xgQD9F6ACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgDyv9pzxZ8M/A/wW8ReK/i3q+o2Hh3ToBNJ/Zuqz6fd3MwP7q3hlgdJN8jYQKGwcnPGSAD+b3xNq8ev+ItT1uG0a1iv7ua5jt2uJJzCjuWWPzJCXfaCBuYknGSc0AZtABQAUAfWn/BLD7Uf22vA4tp5Ix9n1PzQjEB0+wzZU46jODg+goA/fSgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoAKACgAoA/HP8A4Kw+KPiD8T9Y0TVdK1SW58B6Pc63bQadbj91BLp11DZXN7O2cM73MxiQfwoExzI1AH5132n3+mTLbajZT2srRRzKk0ZRjHIgdHAP8LKysD0III4NAFegAoAKAPt3/gkD4Q1PX/2urfxFawn7H4Y0DULy6kI4HmoLdFz6lpsj2U0AfuXQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAfG+u/sd+JvFmkfFH4J+JLPTv+ER8Uzapq/hHxXbzCS50qe+v4b+Wzu7RyPMVbqBGV0JDICrbSc0AfCf7WP/AATd/aA8HeHJvirp3hDwnfW+k2wj1e28JXt3Mzomf9Mjs54x5EYULuhid1TkqqoMKAfBdABQAUAfrh/wRA0XQl8EfFDxDGY21mXVbCymHG+O1SF3j9wGd5f++PagD9F9D8d+HNf8S+IPB9jeMus+GZIF1CzmjMcixzRh4pkB+/E43KHXI3RyL1QgAHQ0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAFe/e5hsriaxtVublInaGFn2CRwDtUt/CCcDPbNAH8yvxj+F/wARfhJ491Dwp8UPBt54Z1pmN59iuMEGKR22vG6krIhIYB1JB2nuDQBxNABQB9df8ExP2g9T+Cf7TOi+HZZGfw98Q5ofDupQDoJpHxazgf3klYL/ALkj+1AH63/tWte/DHS9N/ai8L2skmp/Dkga7bQ8NqvhuaRRe2zerRfLcxE/deEgcO2QDd+H37YP7MXxO0uPVfCXxv8ACUiyBSbe81GOyuYyeitDOUkU5OOn0zQB6/FNDPGk0EqSRyAMjocqwPQgjqKAH0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAee/Fv4AfBz456Q2jfFX4faRr8BMbCWeHZcx7G3AJOmJUGcghWGQSDwTQB+dGm/8EePCfiH40eKr4fF+1tfhhpGqSRrY2G59VtjsSU2cskq+VH5aSp+9zISuMgHOAD5++JX/AATH+KcWt6rc/s7eLfCfxY8NWt28MMmk67aC/g43CGeJnCmUKRnYxz1wvQAHp/7A/wCy34E+D/xl0z4jftP/ABX8DeE/FHh+WR9G8FXuv2f9oLdbSqz3a+YRFsyWSPO/cFY7doDAH6V/tS+JfD8P7KvxR8QPqFtc6ZL4M1ZY54pFkilMlrJGgVlyDl2UcdzQB/NvQB7T8DP2x/2if2d7iEfDf4jahHpkTAtot+xu9OkHceRISEz/AHoyre9AH6vfsef8FRPhv+0NqVj8PfiNpsPgjxzdkQ2qmbfpupynokEjfNHIe0T5zwFdicUAfcFAC0AFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFAHg37bP7R9v8AswfADXfiDbvC2v3ONL8PQSYIk1CYHYxU/eWNVeUjuI8d6APxLl/a/wDiSP2btU+AVpqd9E/ijxVfeIvE2sG5JuNUjnjhAt2brtaSOR5Ofnyo6bgQD6//AOCeXwmsPgj8avg9BrOkWep+Nfid4c1TxVdmeIyHw/of2dvsJh7LPO6uXcjIQrGMbmJAPBP+CjP7K/i34GfEa0+JWpNNdad8SZbnVbqY4ItNWeVpLm2JXjHzq6HPILD+EmgDw7RP2jfiroPwM8Qfs7WXiBz4K8RX9vqFxaSZZoXibeyRNn5EkdY2dcYJjUjGW3AHmNABQBJbzXEFxFPaSyRzxurxvGxDq4OQVI5BBxjFAH63/tyftU/Hn9lLxj8FPFvhPxK09xrXg2OPxJoupKZbK/ngMZZ3jyDHKWmceYhVuACSBigD6N/Y+/4KD/Cb9q9V8MQwS+F/HcNuZ59Bu5A63CqPne1mwBMo6lSFcDJ2kAtQB9TjmgBaACgAoAKACgAoAKACgDwf9ufx34m+Gf7Knj7x14N1m40nXNItbWewvICA8Uv2yAA88EEEgggggkEEGgDM/Ye/a40P9rb4TjxEYY7DxZoRjsvEmnIDsiuCpKTxZ/5ZShWZR1UhlOduSAfRdABQAUAFABQAUAfGP7af/BRr4Y/APwfq3hz4YeKtG8TfEt2NnbWNs/2mDTJD96e5Zfkyg6RbtxbAIA3EAHyP4J/4LYfFXRvDNlpnjf4R6F4k1mA7bjU4NQewFynYmFY3VX65KkKeyigD9MP2X/jvD+0p8FtC+MNv4Uu/Dqa0Z1+w3E6zFWilaJmSRQNyFkOCVU+1AHq1ABQAUAFABQAUAFACUAfiP/wVv/aMg+K/xyt/hV4bvxPoHw4SS1naN8pNqsmPtB46+WFSL2ZZPWgD4QoA/Qz4A/tq/HDXf2ZvibpN2mjWMPwp+HMWl6P4ksbMxavHJPeW9raxm43kAKhkI2qCSgYnIzQB3/7TvhxfF/wuuvjF8R/i/pFn4O+Jfwo0vxCmgX2oI18fGFrbQi0ls7d23EyKZEkeMAbDKHz8poA+BPhb+zL8cvjTAl38NfAN1rFtIxVZ/tMEEWQxU/NK6jgg/lQB7vpP/BJf9tLU4zJc+C9B03ABUXXiC2JbPp5TP+uKAH6j/wAEmv2utJjE99YeDoU9ZPEcMYP4uAKAOq8F/Ab9mj9kqbw/4/8A2sYvE2teIrJ3vLTRdC1HS9R0q6uoW3RrIIJWmRc7cebsRyG6gFaAPFP23v2urr9sD4m6d4zj8LP4d0rRdMXTLGwkvBcv/rHkeVnCqNzFgMAcBByaAPCvC/ijxD4K8Rad4t8J6xdaVrOk3CXdje2shSWCZDlWUj/9R6HigD+gn9g/9pXX/wBqb4DWfxA8V+G30vWrC7k0e/mRNtrfzxIha4gHZW3jK/wuHAJAFAH0XQAUAFABQAUAFABQAUAfD3/BYWTU4/2RN1hqFxbwt4n05LyOKQqtxCVmwjgfeXeEbB4yqnsKAPH/APgh3bY8M/Fq7x9+/wBJjz9I7k/+zUAfqDQAUAFABQB5h+0R+0R8Ov2Zvhxe/Ef4jaiY4Ij5NhYwkG51G6IJSCFT1Y4ySeFUFiQBQB+JP7RP/BRv9pP9oGW/0mTxXJ4S8KXTuE0PQ3MCtCTwk84xLNxjOSEPPyDpQB8uUAFAHtPgb9sr9pf4afDKP4Q+APitqmg+GYbiW4ihskijniMhy6pcbfNRSxLYVhySe9AH7P8A/BNb4ieI/iZ+x94N1zxbq91qmq2kt9p095dztNPMIbqQIZHYks2woMk54FAH1BQAUAFABQAUAJQB8dfto/toeGvh9oV58Ovhh8ZfAWieLblpLPVNVvtQe5k8PptG5ktbVJZZLkhjsUqFUjLHOFIB+Z3wU/Zb/Z0+PHxAvPCsf7Zlvp99OM2smseGJbSXU7puWMTTXAVhuzwzrK2fuUAfRnhz/giH4qk1DVk8WfHTSYrBbY/2TNp2lySSyzn7pnjkZQiDuFdic9RjkA8r8d/B/Vv2Wf2C/H/h/wAVy2j+IvH/AMTIvDnm2sm+Kex0lpW3xt3UzxS9QOoBAPAAON/bb8Nhfg7+y/4+jjBXVvhpDpLyY5LWcm7BPsLnA+hoA/S79g7SfgF8fP2WvBnie8+EfgS61jTLMaFrJbw/aGUXlqBGzMdmd0ieXLnP/LSgD2y4/ZU/Z1uCSPhD4etyTkm0gNtn/v0VoA8P/at+Ff7J37P/AMJNT8f6n8DdKubtj9ns7r/hEm8RLbTsCRJNDLKiCP5SN0kqDJAySQCAfjP8Vvi/4++I7SQX+qSx+Eku2bTtPstJg0jTlIyFb7JagQCUKeuXYAkbjQBt+Av2Of2oPidpNh4g8EfBDxTqOlapGJrK/Np5FvPGejrLKVUqexzg9qAPrz9n3/gjV8TfEGp2us/tC+I7PwvoyMry6TpU63Wozr3QyjMMIP8AeBkPsOtAH6z/AA/8AeEPhd4O0rwD4D0ODSNC0W3FtZ2cAO1F6kknlmJJZmJJZiSSSaAOhoAKACgAoAKACgAoAKAPy8/4LGftPeF28O2P7L/h17fUNZe7g1jxBKDu/s5EBaCDjjzX3byP4UC8fOMAHyV+xB+3rqn7HEeu6OPh5aeJ9H8SXcF1e/6a1tdRGJWUeW21kIwxOCv4igD9XP2f/wDgop+zL+0HJb6RpPjD/hGfEU+FGi+IdtpM7n+GKTcYpTnoFfcf7ooA+m80AGRQB5v8aP2h/hJ8A/Beo+OPiL4vsrS10/KLaxSpJd3M+CVghiB3NI2OnAAyWIAJAB+Bv7Wn7VXjn9rH4nT+NvE5ay0mz3W+haMkhaLTrXOcejStgF3x8xAHCqoAB4lQAUAFAH1n/wAEzPA/w4+J/wC0Xd/DX4m+FbXWtP8AE3hXVrC285NzWk5jUmeMnhJBEJQr4ypYEYNAH66fsRfs6+Kv2XPg3cfCjxTr+nayYNevr6wurLeA1nLsMYkDqu2TIYsBkDPBNAH0DQAUAFABQBwnxi+OPws+AnhOXxp8VvGFloWnIGEQlbdPdSAZ8uCJcvK/soOOpwOaAPyF/a4/4KtfE/4y/bfBXwVW88CeD5d0Ml2ku3VtQjPB3yKcW6EfwRnd6uQcUAfDuiaFr/i3XLTQPD2k3uratqcwhtbS0haae4lY8KqqCWY0AfrJ+xP/AMEn9M8KnT/if+1BZ2+p6uu24svCQYSWlo3VWvGHEzj/AJ5AmMfxF+gAP0xREjjWONQqKAFCjAAHQCgD82/+Clv7I3xh+JHhl9a+GGl+b4P+HtrFdaT4Y03DSXU11Lcy6pdbCdzSIfs21BkkNJt54IB8h/F7xjYfEv8A4Ju/CG4JZtV+GvjK+8J3YII2xzwSXER+hjWJfqhoAp/8E6v2z1/ZV+JFzo/jOSaT4feLWji1YRqXbT7heI71EHJ2glXUDJQgjJRQQD91YfGfhKe2sbuPxPpXlanbx3dkxu41+0QSAFJEyfmUgggigDWZYp4irBZI5FwQeVZSP1FAHxT8UPgz8A/2vvjBf+GNIm1fxWfDEi2Ot3RupF0HwqowJrWyhUJFJqE+whmPmeUCXYgrEjAH2hp2n2Wk6fbaXptpFa2dnClvbwRKFSKJFCqigdAAAAPagCzQAUAFABQAUAFABQAUAFAHm/7RPxo0P9nz4M+KPi1rux00KyZ7W3Zsfart/kt4B/vyMgOOgye1AH82/jHxd4g8e+K9X8a+K9Rkv9Y1y9m1C+uZDkyTSMWY+wyeB0AwB0oAx6ADNAHvXwj/AG6v2qfgnbw6b4K+LmqyaXAAsem6rt1C1Rf7qLOGMY9kK0Adh8Wf+Cmn7Wvxd8L/APCI6j43tfD1jKpS7bw7amxnu1P8Lyhi4XHUIVB75oA+WJp5rmVpriV5ZHO5ndizMfUk8mgBlABQB3XxP+CXxL+DkHhi4+IfhqXSovGGjQ69pDs6uJ7SX7pJUna4GCyHDLuXIGRQBwpBFAH6k/8ABEKHwNJqfxPmlt4D4yihsBbyvzKumsZPMEfovmiPfj/pnntQB6P8cP8AgsP4b+Ffxj1v4beHPg9ceI9M8N6jJpd/qj6wLV5Z4nKTeTF5TgqrBgCzDdjOBmgD7y+GnxA0D4rfD7w98SvCzzNpPiXToNStPOTbIscqBgrjswzgjJ5B60Acl8b/ANp74G/s52+nT/GDx7aaE+rOVs7fypLi4mA+84iiVnCDoXI25IGcmgDy67/4KcfsSWunvfj41QzbBnyItHv2lb2C+TQB8qfH3/gtJafZ7jQ/2cvAUxnYFF17xGoCp/tRWiMdx7gyOPdDQB+anxO+LPxJ+M3iefxl8UPGOpeItWn48+8l3CJf7kaDCRIOyoAvtQB63+zZ+wd+0H+0xd2934Z8LS6J4YkYed4k1iNoLMJxkwgjdcNjoIwRnqy9aAPu74o6X8BP+CUXwe8r4c20HiP43eLbSS20/WdSjV7qJCNsl0I+Rb26H7sa8yPgMXCsVAPzx8G/tn/tT+A/EkvinQPjr4te9uJfOuFv9Qe9t52zk74Z98Z/754HTFAH3d8Av+C0kbvbaF+0b4BEYJCNr/hxSQP9qW0c59yY3PslAEv/AAVA/aI8UeN/APw08cfs2eNdT1DwLFcXd9quveHZ3+z298BGttDdMnzQyKpmYJKFOTkDI4APkD4A/tMeBPhN8KND8PeJfCR16/8ADnxSsvGrafI2yLUrMafNbyJvwwDxv5bAMMNvA5ANAHvvxc/4Ky+F9W0a70j4L/s0eGtCvLiBo4tY1m3tbiS2c8b0t0i2EjtucjOMqRxQB+fXiXxV4k8Y63ceJPFWuXmq6pdNulurqUySHHQAnoB0AGAAAAABQBo6P8UPiX4etzaaB8RPE+mQHrFZ6vcQofwRwKAP12/4Iu+Kb3XfgZ47sNU1Ga8u7Xxe13I80heRvPtIfmZiSSSY25PpQB+hlABQAUAFABQAUAFABQAUAJ0oA/If/gsz+0Ode8Z6D+zl4ev82XhtV1rXhG3D30qEW8Tf9c4WL/8AbcdxQB+aFABQAUAFABQAUAFAHpn7NnwW1f8AaD+NvhX4T6SsijWr5RezoM/ZrJPnuJj6bY1YjPVto70Afsh/wUb/AGULv4xfsx6boPwr8Lpd698OnhuNEsoT+9exji8qa2iz94mNY2C9WMSgZJAIB+XX7efwBsfgT8TPDK+HtBOk6F4p8H6Rqtrb4YCK4W2SG6Q7ud/mxmRs85l96APff+CYn7K37U3hf47+HvjPP4OvfCfg6G3ni1KfWlNs+pWc0RxFFA37x8v5bhioQbAcnABAO2/a0/4Jn/Daz+K2ufFTV/2mfD/gXQvFuqy6m2m6tZma9FxPIXljtUSQPckuzFEVd3IHOMkA928Z/FP4/fBn9mq18Jfsn/s8+LbjTfB+nWWj6drPiTTHN/ertIe5g0xMzYUKXZ51jAZlAjbPAB+NPxP8Z/Ejx7421PxJ8WNa1fU/E88m29l1XcLhGHSMowHlqvQIAAo4AFAHR/s//s6/FL9pXx1b+BPhjoLXUzEPeX8wZLPToe8txKAQi+g5ZjwoJ4oA/Qb4ff8ABEJt8dx8VfjkCowZLTw/pnJ9QJ524/79UAfX3wd/4J0/sm/BeWDUNH+GkGv6tAQy6l4jk/tCUMP4lRx5KHvlYwaAPpRI44kWKJFREAVVUYCgdAB2oA/Bn/gq7r17rH7a3i2yupS0Wj6fpdhbKT9yM2ccxA9Pnmc/jQB8gUAFAHdfCD42/En4GeJv+Ep+HHiOXTppU8m9tHUS2eowfxQXMDfJNGeflYcZyCDg0AXfjr43+GPxG8VweMvht8PH8EvqVosut6NDOJNPi1HJ8x7EfejgcbWEbZ2MWAO0CgDzigAoAKAP1X/4Ic62zQfFzw4V+VH0e9B92F0h/wDQRQB+qNACdKAGrLE7MiSKzIcMAcle/PpQA+gAoAKACgAoAKAOU+K3xF0D4R/DfxJ8TfE8uzTPDWnTajOM4MmxSVjX/adtqKO5YUAfzS/Efx74g+KPj3xB8RPFNwZtV8R6jPqN02eA8jltq+iqCFA7AAUAc5QAUAFABQAUAFABQB9Wf8EvrjxbD+2n4Fi8KXJhW4W+j1TK7kksBayPKrD3KJg9mCntQB+/dAHlX7Qn7MXwe/ad8M2/hn4seHGvVsHaXT762mMF5ZOwAYxSjoGAGVYFTgZBwMAHkngn9ge++H0cuj+F/wBrn45WXh2UbDpaa5Adif3Y5GhJi+sYU+4oA9W+GP7K3wO+E+r/APCU+HPBiX3idv8AW+I9cuZdU1aQnqftVyzyLnuEKj2oA9awKAOJ8d/A/wCDfxPnS6+Ivwr8KeJLiPASfU9JguJVA7B3UsB7ZoA3PCXgfwZ4B0ldB8DeE9H8Paah3C00uyjtYc+uyMAZ96ANugAoAKAPwF/4KlDH7cPxC4/g0r/0221AHyjQB20XwW+KFz8NP+FxWHg+8vvByXD2txqtmUuI7OVDgrcLGS9vnIwZFUNkYJzQBxNABQAUAFABQB+oH/BFG50zQJvixruqXTxi4j0m2iRLaWUnZ9pdzlFI/jTjrzQB+impfHK7vpptO+Gfwp8Z+Lb6MY3yac2j2CN/t3V+IgR/1yWU+xoA838W/CT9rb4xxTJ4/wDj3pXwn8NurGXSfAVu098YsciXVbkIykDOTFEo470AfGXx/wD2fbD9kL4lfCL4lfs7fHrxtcN428W2mhaz9q1kXRvi7xuZGljCrIrJJhkdWHzAgjpQB+tNABQAUAFABQAUAfmV/wAFn/j/AP2N4S8N/s66He4udfddd11UblbOJittE3s8oZ8f9MF9aAPyQgt57ueO1tYXmmmcRxxopZnYnAUAckk8AUAfq9+wz/wSp0iLSI/iZ+1V4fF5d6hbH+zvCMzsi2sbrjzbsoQ3m4PyxgjZ1bLcIAfP/wDwUS/4J9QfsvyWvxN+F9zd3vw+1a6+yS2103mT6PdMCUjaTrJC4B2ufmBG1iSQzAHw7QAUAFABQAUAfpL/AMET/hsdW+Kfjv4q3NvmLw9o8OkWzkcCe7k3sR7hLcj6PQB+wdABQAUAFABQAUAFABQAUAfjz+21+2H+054z/aM8Y/A/4S/EOLwNofg+Z7OOKLWbbR5r541XzZXvJ3jyxJbbGrr8oHBOTQB8d/tH/B34+/CzxHpmp/tEfa28ReK7P+0Ipr7WE1G7mgQiNWlkV3/ugLlui+goA8hoA/T/AP4JNfCL4ffGb4VeO7DXn1XS9b0TWY0TU9C1CXT7x7K7t8NbztGdtzCWgYiOZXUHdgDcaAO9+JX/AARR+HWra1pt18K/itrOg6e8/wDxNLfV7eO/cRYJ3W7IIvmzgbXyMHOeMEA9T8Gf8Eh/2QvDenx2/iHS/Enim7C4kur/AFeSHc3chLfy1Uexyfc0AfIP/BTb9iP4Dfsy+B/C/jj4T2+uabd61rDabNYT3hurUxiF5C4aTMiOCqjG4ggngYyQD87qAPS/2b/glqn7Rfxo8NfB3SdUXTJdfnkWS+eAzLawxxPLJIUBG7CxnAyMkjmgD+hz4EfBLwX+zz8LtF+FXgO2KadpMX7y4kUede3Dcy3EpA5d259hhRwoAAPzd034uft1ftf/ABN8YaB4F/aM8E/DCHwpql9ZSeHI702l/DBbOVabYsLzzqMYZ9+0MD8q8CgDl/2VP2zfj9rfjn4mfDfXPjHdfEfwxZeBvEWp2N9e6comlmtbRnjlh8xRIqscjZJkEdVB6AHhnw8+KusfHn9p34EeAhqWsXXhfwr4nsrLSI9RkVriaN9Ua5ku7hU+T7S6sokYZz5Q5oA/f6gAoAKACgAoArajqFlpOn3Wq6ndR21nZQvcXE0hwkUaKWZmPYAAk/SgD+b39pb4u63+0z+0P4n+INtb3V03iDVBaaLZxozyC0UiK0hVByWKBOAOWY+tAH6o/wDBPv8A4JvaR8Cbew+L/wAaLG21P4iSxrPYWDASW/h8EcY7Pdc8v0TonOXIB99UAeCft4eCLr4hfsi/E7w5YaYL+8GiPf28PG4vaulxlc/xAREjuelAH4IfA/4HfEP9of4g2nwz+GOmQ3us3cUtx+/nWGGGGNcvJI54VRwO5JIABJoA7L4z/sVftL/ALTbzX/iV8Mb2z0OyeNJdXtZorqzG9gqEyRsduWIA3AHJHqKAPD6AJUtLqS3ku47aV4YSBJIqEqmeBk9Bn3oAioA/dT/gkj8Mz4E/ZIsPEl1beXeeN9Vu9ZYsMMYFIt4R9NsJYf79AH2pQAUAFABQAUAFABQAUAFAH4Cf8FQ/B0vhD9tLxw5UiHXkstZgJ/iWW2jVz/38SQfhQB1H/BVTxHN4m+O/gy0iDyLYfDzRgFXnmXzpicfRx+VAHxUeKAPsX/gnr8fh8K7P4s/DiDV49K1b4ieHFsdAv55p4YLbVFMkUTNJBFLIjYuWZCEO50VMguDQB9tW37eWqw/syeHNP0nxtp958TYdJ0yTxDqupW88cdv591Jbt5fl27xG7Lwugim8nBO45wRQB33xB/4KE2PgP4uXPw01jwzpemafa+N7Pwu2t3epsNlvugN3M8DImNiSkh45JFUMjSBOlAHgf/BTX45fD/4zfsoWk0UkEOt6d8SbvTdOt0l81p7ezN1CbtGHDQyxNC4cfKTIACcGgD8nqAPtr/glVdaB4H+LPjb45eLILuXSPAHhV5JBaxebN513cwwJsXIySplGM9zQB+k3hP8Aaau/iT8XrcaJ4i1bRPDNj4h1DwzFoWqeHBbXOsajBY72Xf5jzJFG0sTeZJHCuZI1JJIBAPzo8F+OdIvf+CmeoeNtB0LU/D8GvwatdXel6jbPbXFpd3GgzNdQyIwB+W4aTnGGwCOCDQB80/ArxJ4k8IWvxH8ReFdRlsb6HwVdW32iI4dIrm8tLeXaeqkxzOuRzzQB6P8A8E19AbxF+2v8NLcLlbO8utQbjIAgs5pB+qigD+g6gAoAKACgAoA+M/8Agqx8c2+EX7MF/wCF9KvPJ1v4hz/2Db7Ww62mN9249vLxGf8ArsKAPiX/AII7fAjTviF8bNZ+LfiCxW4sfh5axNp6yLlP7TuS4jk54JjjjlYejMh6igD9pRxQAtAFLW9NTWdGv9IkIC31rLbMSMgB0KnI/GgD+fX9kDx/N+y/+2f4dufEl1HDa6Vr1z4Y1uQN+7WGRntZXJ7qjkSf8AoA/e34o/D3Qvi18OfEnw28SwrJpviTTZ9OnyM7PMQhZF/2lbawPYqDQB/M1418J6v4D8Ya34J1+Aw6noGoXGmXaEEYmhkaNuvbKmgD9Rf+Ce9/oPj7/gnN8bPh3q2nWszaNFrZlBiXLJLp4mhdu5ZZEcqT02DHSgD8p7KzudRvYNPs4mluLqVIYkXq7sQFA+pIoA/p1+Efga0+GPwt8JfDuxjVIfDmi2emDaMAtFCqM31LAk+5oA62gAoAKACgAoAKACgAoAKAPyW/4LcfDc23if4c/Fu2gGy/srrw/dyAdHhfzoc/UTTf98UAeAftI+K/Gkf7ZXw/1HwEbN/Etr4f8FW+lpeqj28lxNplqVjlD/KY3M+1t3GGOSOtAHvWjf8ABMLwv+0nJfeM/DOoX/wV1vT9TfTfF3ge+sF1GLS78JHKfsUqyofs8kcySRhtwCuAGIAoA+k4f2Ofhb+yF8LfCz+A0u7y+HxB8KXPiXXbwKbq+txqcKCM44igWWSNxGvGVBYsRmgD80P2idAk+HXjvxF4Gt9T1WTXNS+JXiDSvEczancb9Y01ZrCexS4+f94N0jyBiM7jnJKjAB+weg/sU/Dqzv8AV77X/GnjzxHaazfQa0tnqmtndp+pxxLCLu2uoFjuY5TAghdhL86cPuPNAHhX7Zn7LWkX3iTwT4c+HHh+/wDEt/4wtNS0jU9F13xVeTfbdOtIxeKLW5u3mNrdRyjdE+RHudlkBR2BAPmPUP8Agjb8Vtf0618SfDf4gabHp+oRiaPTfFtjPpmp2ZOcwzpGsqF1IwWVtrYyvBBoA9w/Yf8A+Cftt8N/FXxU8B/F2+s9cl/siy0nUJNIuphZ3NvfwSvPYTJIgDtGEtJ1cBWRmQg4JBAPqrwH+xT8Ivhtrz6/4R1bxhYOk9/dWVrba09tbWM168TXTRRwKgIk+zwgq+9AEUKq4GAD85/2nbP/AIR//gqbqMsckhD6P5weRiWb/innXJPc/L1oA+WP2d/D7654J+Ok4jyunfDl7rPoV1bTj/INQB7/AP8ABHHw42sftZXWslfk0Lwtf3WSM4aSSGEc9jiVv1oA/b6gAoAKACgAoA/Ev/gsh8QtU8SftOWPgSbemm+DtBt0t0P3Xmuv30so+q+Un/bOgD6G/wCCI2t+Fz8M/iL4ci1G3HiNddgvp7QsBKbI26JFIB1KiQSgkdCRn7wyAfpdQAUAFAH8+H/BQ74G+JPgx+1B4zmvtGuIdB8VanPr2i3vlEQXEVyxldFfoWjkZ0Zc5GAejAkA/SX/AIJcftf+PP2jPB2u+BPiPYwSan4GtbCK01W3hdft1qUaP9+SSDOpiBLDG7fnaMEkA+Ef+Cs/wrX4e/tZ6j4ks7byrDx1pttriEfd+0AGCcfUvFvP/XSgDsf+CUviG4u9K/aA+FcUuG8Q+A576BD0MkKSw/ni6H5UAfMH7HXhCPx3+1N8LfDE8Xmw3HiexnmTGd0UMgmcEem2Ns+1AH9I1ABQAUAFABQAUAFABQAUAFAHyD/wVV+HK+Pv2O/EuoRQCS88I3lpr8B25IVJPKm/8hTSH8KAPya+POrzH9pDwZrsUhWRdA8DXEbjqCuj6eQf0oA/ZTxdcXXwY/a98O+MfMZPCfxpsE8K6pk/u4PENmryafMfQzQGaD3McftQB7F8WPAsXxN+GniTwHLOLd9a06W2guP+fe4xmGYe6SBHHutAH4nftgeE/Gnij9onSvjvceFLyy0XxVrOi6bfP5eIoPEEVvBFf2gHd1mglGe+0+lAH7vUAeLeI7dvEv7Wvgy1RN0Pgjwdq+rXDY+5PqFxb21uM+pS2u/++TQB6r4n8R6P4O8Oap4s8Q3i2ul6PZzX95O3SOGJC7t+AU8UAcd8CNB1bTvA3/CS+JrRrbxD4zvZvEurQvndby3ODFbnP/PC3WCD/tj70Aei0Afj/wDt8Rf2Z/wUYg1RFx/xQdxfSEf3Y9MvwT+UdAHn3/BMn4XXPxV8O/tE+GrS38ybVPh5Lo9vxn/SLhnaEf8AfcAP4UAe7f8ABGf4P+OfBniz4m+KfHHgvXfD7/2fp+nWg1TTpbUzb5JZJNnmKN2PKjzj+8KAP1LoAKACgAoAKAPkz9rb/gnN8J/2rvFNr4+1DxDq/hfxPHDHaXV9YhZ47y3QHYrwyHAZc8OpHHBB4IAPN/2Pf+CYurfsv/tAS/FfUvinb6/pVhp9za6VBbW0tpPLJMApNyu4oVVN2FDMCxVuNooA++6ACgAoAwfGngLwV8RtBm8LePvCuleIdIuCDJZalapcQsR0O1wQCOxHNAFzw/4a8O+E9Lh0PwtoOnaPp1uMQ2lhapbwxj/ZRAFH5UAfnn/wWs+GX9t/CHwX8VbS1DT+GNZk0y6kA5FteR5BJ9BJAg+slAHyn/wR/KN+1tJbzXMMcM/hPU45Y5D/AK5d0JKD1PG76KaAOf8A+Cc2j6f/AMPAvCtnBcJLb6ffay1vIp+VwlpcqpHrkc0AfvVQAUAFABQAUAFABQAUAFABQBxPxu8KQeOvg1468G3KK6a14c1GxwwyMyW7qp/AkH8KAPwL+PNibb4kfCXUDk/2n4C8GXOfUrZQwn9YTQB+9Hx2+FkXxi+FureC47oWWqERahol+PvWGq2zrNZ3APUbJkQnHVdw70Aanwn8cj4k/DjQPGj2v2S51G0X7danra3qEx3MB945kkQ/7tAHm5h0n4cftEf8IrrNjay+G/iqza7owuIleO08TWUQFyqZGEee2VJlIwd9vcHq1AHuhZVXczAADJJPSgDy74IJH4nuvFfxkJ3p411FU0p+edGsgYLQj/Zkb7Rcj2uRQBz/AMfLp/H3j7wB+zzZfvLfXrtvE/ikDkLoenSRuIn9ri7a1ix3QTCgD3IDFAC0Afkp/wAFArXz/wBtPxlracr4e+CeoXEvGQpmt7q0XPp814n4kUAdn/wRA8MeR4I+KPjFoiBfarp+mI/Y+RDJIw/D7Qv50AfpvigBaACgAoAKACgAoAKACgAoAKACgAoA8g/a6+E//C7f2bfH/wAOIYBNe6jo8s2nrjJ+2wYmtwPrJGg+hNAH8/37PHxb1L4C/G/wj8UrMSf8U/qaSXkIyDNaNmO5iI/2omkX6kUAdT+zx8WvD/wg/a78MfFSC58nw5p3ip3llCMBHps8jxSPtxniGVjjGeOmaAP6FvAnxC8DfE/w5B4u+HfizS/EWjXJZI73TrlZoiy/eUlTwwyMqcEdxQB0NABQAUAFABQAUAFABQAUAQX1sL2yuLMtgTxPFn03Aj+tAH5c+Pf+CbPxm+J+ufs/W1ydP0OPwt4Qh0nxVqEk6zLZG0u3liREU5lldJ9owdo8s5YADIB+pfRfpQB89fs9+OvDWh/F/wCLv7P9/rUEfifT/FN14qtLATblk0zUI4bgNDkDBWWR/NTqrSBvuuKAOP8A2zfjfo+kad4fuvh9pp8Za38OfE1n4w10aZiWPRNLsxJ9tkuJgdkcjwPJGsRbzG3khSFNAHV/ti/FnwNp3wIudBufHkejp4+XT9L/ALRt9ztZaVfXEcVxfSFATFCLdpv3rYXdgZzQB75oGn6No+habpHh6GCHS7K0htrGOAgxpbogWNUxxtCgY9qAPIfhRpepa1+0R8ZfiHqKJJaWr6N4Q0eXqVhtbX7Vcqp9DcXxB/2oyD93gA9uoASgD8u/+Ch3w98YeDbz9oj45eJdNW20rxXoXhbwb4WuluEc3CNcxTXo2g7k2mzIIYchwRmgD6F/4JT/AA8l8CfsdeHL+7t/KuvFl9ea/ICMEo7+VCfoYoUYf71AH2BQAUAFABQAUAFABQAUAFABQAUAFABQAUAfi7+2N/wTD+PNl8ZPFHjH4HeBF8S+DtevX1S1hsryBJ7F5jvlgMMjqxVXLbSuRs29CCKAMH9n/wD4JIftAfFMXt/8T7hPhhp9q/lQjULYXd5dPjJKQJIoVBnG5nGT0B5IAP1A/Yn/AGZ9Z/ZP+Ed78LNX8W2niMNrt1qdre29q1v+5ljhUK8bM21g0bnhiMEc0AfQFABQAUAFABQAUAFABQAUAFACYHXFAHOfErxTc+Bvh14p8a2dgL648P6LfarFalsCd4IHkWMntuKAfjQB8VfBz/gpV+xp4U8I6DY+KfG91/wlOoWUWo+JNUTw5dbZNWnjRrssyoWJ3jaNoKhURQdqjAByX7ZP/BSP9mvxN8FNY+Fnwl1jUvEcvi1U0/VZ9O0uW2j0/TpZF+1ODOiBpmj3IgAI3OCxGMEA+g/2H9a+F3j74Nx6pH4u8LeJtf8AFdnE2uaVb3kd1/ZtmkXlWuktC/ziK3t9sZDLh3Mz8mQkgHX/ALVPjjwx8FPg3deM9T+JWqeB9K0C0eK10/RRZxTapII9sFlD58MjIchQDFtKrkngZAAv7EOgeLfDv7LXgGDx59qPiLULKbWNSe8ZmuXmvLmW53TM3zNJtmXcW5z1oA9zoAKAMLxd4F8FeP7CDSvHXhPSPENja3KXkNtqlnHdRJOoIWQJICu4BmAOO5oA1bCwsdKsoNN0yygs7S2jWKC3gjEccSAYCqq4CgDoBxQBYoAKACgAoAKACgAoAKACgAoAKACgAoAKAExQAYoAWgAoAKACgAoAKACgAoAKACgAoAKAM/xFott4k8P6n4dvSRb6pZzWUxXGQkqFGxn2Y0AfnNff8ERPhW8RGm/G/wAVwSY4afT7aVc/Qbf50Aeman/wSv8AhXafs4ah8DPAvjHUtF1bV7y21HVfE0ttHPNqk0AYxQzx8bbZXbcsUbLhlDEsckgHyBZ/8Eav2o9K8SB9I+Jfge0ggkzDqcOoXkUyrn7wRYNytjtu/GgD7E+BH/BMvwp4O1/TPiB+0H8SNb+L/inSSsljHrE0r6bZOpyCsUru0pBAxvbbwDsyBQB9sUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQAUAFABQB//Z",
				"images/users/default.jpg",
				0,
				2
			]
		]
	}
}
```

**Comment by antifree** [comment]
Hello,

Please, be sure that you have also updated js and css to the latest version (1.3.1).

To show byte array property use such attribute. By default it is hidden

```c#
        [MetaEntityAttr(ShowOnCreate = true)]
        public byte[] Picture { get; set; } 
```

**Comment by Rudnytskyi** [comment]
> Hello,
> 
> Please, be sure that you have also updated js and css to the latest version (1.3.1).
> 
> To show byte array property use such attribute. By default it is hidden
> 
> ```cs
>         [MetaEntityAttr(ShowOnCreate = true)]
>         public byte[] Picture { get; set; } 
> ```

thanks, it worked!
