### ISSUE TITLE
The search of related data model does not work in Create mode

### ISSUE THREAD

**Issue by AlexandrSurkov** [KorzhCom/EasyData#5]
Hi. I found that search modal can't be opened when you are creating new record.

For example, in the .net core 3.1 sample you can click on "..." button and search employee to make a reference

![image](https://user-images.githubusercontent.com/17044185/101318084-c951b580-3870-11eb-805f-6f7dfae3d813.png)

And sub modal window will be opened:

![image](https://user-images.githubusercontent.com/17044185/101318208-00c06200-3871-11eb-8d69-040c3beae67e.png)

_(p.s Look at the name of sub modal window. May be it should be changed :)_

But when I want to create new order buttons "..." that should show modals don't work:

![image](https://user-images.githubusercontent.com/17044185/101318422-5e54ae80-3871-11eb-8b66-36a8da446298.png)

**Comment by antifree** [comment]
Hello, we have published version 1.1.2. It should fix problem #6

**Comment by ilchenkob** [comment]
Tested on EasyDataBasicDemo.NetCore31.
The bug is still reproducible after updating NuGet packages to v.1.1.2 and rebuilding the solution.

**Comment by korzh** [comment]
The bug was in the JS part of the library. So, please update the links to EasyData script on your pages as well.

It must be:
` <script src="https://cdn.korzh.com/ed/1.1.2/easydata.min.js" type="text/javascript"></script>`
now.

**Comment by ilchenkob** [comment]
That helped to solve the issue.
Thanks!
